import Head from "next/head";
import { getMenu } from "../../libs/menus";
import { getPage } from "../../libs/pages";

export default function Home({ context, menu, page }) {
  return (
    <>
      <Head>
        <title>Dominik Giroux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="alternate" hreflang="en" href="/blog" />
        <link rel="alternate" hreflang="fr" href="/fr/blogue" /> */}
      </Head>

      <main className="section-container text-center">
        <h1 className="animate-fadeIn text-5xl font-black">{page.title[context.locale]}</h1>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const menu = await getMenu("main");
  const page = await getPage("blog");
  return {
    props: {
      context,
      menu,
      page
    }
  };
}
