import Head from "next/head";
import { getMenu } from "../libs/menus";
import { getPage } from "../libs/pages";

export default function About({ context, menu, page }) {
  return (
    <>
      <Head>
        <title>Dominik Giroux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="alternate" hreflang="en" href="/about" />
        <link rel="alternate" hreflang="fr" href="/fr/a-propos" />
      </Head>

      <main className="text-center">
        <section className="mx-auto max-w-7xl animate-fadeIn pb-16">
          <h1 className="bg-gradient-to-l from-teal-500 to-purple-500 bg-clip-text py-16 text-6xl font-extrabold text-transparent">
            {page.title[context.locale]}
          </h1>
          <p className="font-black text-zinc-600">{context.locale == "en" ? "Comming soon" : "Bientot disponible"}</p>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const menu = await getMenu("main");
  const page = await getPage("about");
  return {
    props: {
      context,
      menu,
      page
    }
  };
}
