import Head from "next/head";
import { getMenu } from "../libs/menus";
import { getPage } from "../libs/pages";
import { getSection } from "../libs/sections";
import Hero from "../components/sections/hero";
import Title from "../components/sections/title";
import IconsList from "../components/sections/iconsList";
import Clients from "../components/sections/clients";

export default function Home({ context, menu, page, sections }) {
  return (
    <>
      <Head>
        <title>Dominik Giroux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="alternate" hrefLang="en" href="https://www.dominikgiroux.com" />
        <link rel="alternate" hrefLang="fr" href="https://www.dominikgiroux.com/fr" />
      </Head>

      <main className="relative animate-slideTop text-center">
        <Hero context={context} hero={sections.hero} />
        <Title context={context} title={sections.title} />
        <IconsList context={context} list={sections.iconsList} />
        <Clients context={context} />
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const menu = await getMenu("main");
  const page = await getPage("home");
  const hero = await getSection("hero");
  const title = await getSection("title");
  const iconsList = await getSection("iconsList");
  const sections = {
    hero,
    title,
    iconsList
  };

  return {
    props: {
      context,
      menu,
      page,
      sections
    }
  };
}
