import Head from "next/head";
import { getMenu } from "../libs/menus";
import { getPage } from "../libs/pages";
import { getSection } from "../libs/sections";
import Hero from "../components/sections/hero";
import ServicesList from "../components/sections/servicesList";

export default function Home({ context, menu, page, sections }) {
  return (
    <>
      <Head>
        <title>Dominik Giroux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="alternate" hreflang="en" href="/" />
        <link rel="alternate" hreflang="fr" href="/fr" /> */}
      </Head>

      <main className="relative animate-slideTop py-8 text-center">
        <Hero context={context} hero={sections.hero} />
        <ServicesList context={context} servicesList={sections.servicesList} />
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const menu = await getMenu("main");
  const page = await getPage("home");
  const hero = await getSection("hero");
  const servicesList = await getSection("servicesList");
  const sections = {
    hero,
    servicesList
  };

  return {
    props: {
      context,
      menu,
      page,
      sections
    }
  };
}
