import Head from "next/head";
import IconsList from "../components/sections/iconsList";
import { getMenu } from "../libs/menus";
import { getPage } from "../libs/pages";
import { getSection } from "../libs/sections";

export default function Home({ context, menu, page, sections }) {
  return (
    <>
      <Head>
        <title>Dominik Giroux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="alternate" hrefLang="en" href="https://www.dominikgiroux.com/services" />
        <link rel="alternate" hrefLang="fr" href="https://www.dominikgiroux.com/fr/services" />
      </Head>

      <main className="text-center">
        <section className="mx-auto max-w-7xl py-8">
          <h1 className="animate-fadeIn bg-gradient-to-l from-teal-500 to-purple-500 bg-clip-text text-6xl font-extrabold text-transparent">
            {page.title[context.locale]}
          </h1>
        </section>
        <IconsList context={context} list={sections.iconsList} />
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const menu = await getMenu("main");
  const page = await getPage("services");
  const iconsList = await getSection("iconsList");
  const sections = {
    iconsList
  };

  return {
    props: {
      context,
      menu,
      page,
      sections
    }
  };
}
